a = int(input("first number: "))
b = int(input("second number: "))
print("basic arithmetic operations with whole numbers", a, "and", b)
print(a, " +", b, "=", a + b)
print(a, " -", b, "=", a - b)
print(a, " *", b, "=", a * b)
print(a, " %", b, "=", a % b)
print(a, " //", b, "=", a // b)
print(a, " **", b, "=", a ** b)
print(a, " **", 2, "=", a ** 2)
print(a, " **", 1 / 2, "=", a ** 0.5)
