a = int(input("first number: "))
b = int(input("second number: "))

print("relational operators for", a, "and", b)
print(a, " ==", b, "=", a == b)
print(a, " !=", b, "=", a != b)
print(a, " > ", b, "=", a > b)
print(a, " >=", b, "=", a >= b)
print(a, " < ", b, "=", a < b)
print(a, " <=", b, "=", a <= b)

print("logical operators")
print("not(False) = ", not(False))
print("False and True = ", False and True)
print("False or True = ", False or True)
print("bool(0)  bool(1) :", bool(0), bool(1))
print("int(False) int(True) :", int(False), int(True))
